import OpenAI from "openai";

const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
const clean=(v,n=4000)=>typeof v==="string"?v.replace(/\u0000/g,"").trim().slice(0,n):"";
const arr=(v,n=30)=>Array.isArray(v)?v.slice(0,n).map(x=>clean(x,500)).filter(Boolean):[];
const MODES=new Set(["freestyle","hook_ideas","full_song"]);
const ENERGIES=new Set(["rugged_reflection","motivational_pressure","grown_woman_vibe","scorpio_shadow"]);
const COMPASS="Pour into the woman. Speak to the soul. Admit the shadow. Never fake the story.";
const IDENTITY="Real Ninja Poetics is grown-man survival music—rugged storytelling, quiet motivation, slick humor, spiritual reflection, and intimate records for women who value genuine connection. It carries love and darkness honestly without glorifying destruction or pretending to be something I’m not.";

const schema={type:"object",additionalProperties:false,properties:{beat_read:{type:"object",additionalProperties:false,properties:{tempo:{type:"string"},mood:{type:"string"},sections:{type:"array",items:{type:"string"},maxItems:10},vocal_pockets:{type:"array",items:{type:"string"},maxItems:8},uncertainty:{type:"array",items:{type:"string"},maxItems:6}},required:["tempo","mood","sections","vocal_pockets","uncertainty"]},hook_directions:{type:"array",minItems:3,maxItems:3,items:{type:"object",additionalProperties:false,properties:{name:{type:"string"},concept:{type:"string"},seed:{type:"string"}},required:["name","concept","seed"]}},song_structure:{type:"array",items:{type:"string"},maxItems:12},opening_bars:{type:"array",items:{type:"string"},maxItems:6},story_prompts:{type:"array",items:{type:"string"},maxItems:8},flow_delivery:{type:"array",items:{type:"string"},maxItems:8},optional_punchlines:{type:"array",items:{type:"string"},maxItems:8},optional_harmonies:{type:"array",items:{type:"string"},maxItems:8},creative_output:{type:"string"},authenticity_checks:{type:"array",items:{type:"string"},maxItems:8}},required:["beat_read","hook_directions","song_structure","opening_bars","story_prompts","flow_delivery","optional_punchlines","optional_harmonies","creative_output","authenticity_checks"]};

const instructions=`You are the RNP Creative Core. RNP assists Sae; it never invents his identity. ${IDENTITY}\nCreative compass: ${COMPASS}\n\nThe four energies:\n- rugged_reflection: rugged soul, scars, rebuilding, fatherhood, isolation, consequences, quiet power.\n- motivational_pressure: earned confidence and discipline; motivation through lived pressure, never slogans or preaching.\n- grown_woman_vibe: sensual, reassuring, admiring, conversational and respectful. Pour into a woman as a complete person; never degrade her.\n- scorpio_shadow: controlled darkness, discernment, loyalty, temptation, boundaries and withdrawal. Never revenge fantasy or fake toxicity.\n\nVoice: grown-man realism, conversational, rugged, slick humor, spiritual reflection, calm confidence. Use ninja instead of the N-word where natural. Never imitate a named artist. Never fabricate crime, luxury, biography, relationships, trauma or accomplishments. Avoid generic ChatGPT phrasing, motivational clichés, forced rhyme density and preachy explanations.\n\nUse the user's one-sentence thought and supplied truth as the factual boundary. Beat metadata can guide tempo, mood, sections and vocal pockets; mark estimates as uncertain. Always return exactly three distinct hook directions. For freestyle, creative_output is a concise launchpad/pocket map rather than a finished identity. For hook_ideas, focus creative_output on hook development. For full_song, produce a structured draft grounded only in supplied truth. Adaptive signals are preferences, not permission to invent facts.`;

export function GET(){return Response.json({ok:true,route:"/api/creative-core",engineVersion:"rnp-creative-core-1.0",modes:[...MODES],energies:[...ENERGIES],compass:COMPASS});}
export async function POST(req){
 if(!process.env.OPENAI_API_KEY)return Response.json({ok:false,error:"OPENAI_API_KEY is missing in Vercel."},{status:503});
 let b;try{b=await req.json();}catch{return Response.json({ok:false,error:"Invalid RNP request."},{status:400});}
 const mode=clean(b?.mode,40),energy=clean(b?.energy,40),thought=clean(b?.thought,1200);
 if(!MODES.has(mode)||!ENERGIES.has(energy)||!thought)return Response.json({ok:false,error:"Choose a mode, choose an energy, and give RNP one sentence about what's on your mind."},{status:400});
 const input={mode,energy,thought,truth:clean(b?.truth,12000),beat:{name:clean(b?.beat?.name,180),bpm:Number.isFinite(Number(b?.beat?.bpm))?Number(b.beat.bpm):null,key:clean(b?.beat?.key,40),durationSeconds:Number.isFinite(Number(b?.beat?.durationSeconds))?Number(b.beat.durationSeconds):null,sections:arr(b?.beat?.sections,16)},adaptive:{kept:arr(b?.adaptive?.kept),rejected:arr(b?.adaptive?.rejected),rewrites:arr(b?.adaptive?.rewrites),recorded:arr(b?.adaptive?.recorded),vocabulary:arr(b?.adaptive?.vocabulary),avoid:arr(b?.adaptive?.avoid),humorNotes:arr(b?.adaptive?.humorNotes),rhymeNotes:arr(b?.adaptive?.rhymeNotes),beatWins:arr(b?.adaptive?.beatWins)}};
 try{const r=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5-mini",instructions,input:JSON.stringify(input),text:{format:{type:"json_schema",name:"rnp_creative_core",strict:true,schema}},max_output_tokens:6500,store:false});if(!r.output_text)return Response.json({ok:false,error:"RNP stopped before the creative pass was complete."},{status:502});return Response.json({ok:true,engineVersion:"rnp-creative-core-1.0",result:JSON.parse(r.output_text)});}catch(e){console.error("RNP creative core",e?.message);return Response.json({ok:false,error:e?.status===429?"RNP is temporarily rate-limited.":"RNP could not complete this creative pass."},{status:e?.status||500});}
}
