import OpenAI from "openai";
const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
const clean=(v,n=4000)=>typeof v==="string"?v.replace(/\0/g,"").trim().slice(0,n):"";
const arr=(v,n=12)=>Array.isArray(v)?v.slice(0,n):[];
const json=(x,s=200)=>Response.json(x,{status:s,headers:{"Cache-Control":"no-store"}});
const schema={type:"object",additionalProperties:false,properties:{pocket_summary:{type:"string"},suggestions:{type:"array",minItems:0,maxItems:4,items:{type:"object",additionalProperties:false,properties:{bar:{type:"string"},transition:{type:"string"},rhyme:{type:"string"},syllables:{type:"integer"},timing:{type:"string"},start_seconds:{type:["number","null"]},beat_fit:{type:"integer"},authenticity:{type:"integer"},meaning:{type:"integer"},originality:{type:"integer"}},required:["bar","transition","rhyme","syllables","timing","start_seconds","beat_fit","authenticity","meaning","originality"]}},council:{type:"object",additionalProperties:false,properties:{core_emotion:{type:"string"},best_pocket:{type:"string"},rhyme_strategy:{type:"string"},reference_direction:{type:"string"},section_strategy:{type:"string"},no_cap_check:{type:"string"}},required:["core_emotion","best_pocket","rhyme_strategy","reference_direction","section_strategy","no_cap_check"]}},required:["pocket_summary","suggestions","council"]};
const instructions=`You are RNP Adaptive Intelligence, Sae's beat-locked predictive writing partner. The user creates off the dome. You assist; never take authorship.
ORDER OF OPERATIONS: 1 beat fit and section timing, 2 preserve current cadence/rhyme motion, 3 continue the meaning, 4 stay within supplied truth, 5 apply EQ, culture and nostalgia only after the first four are protected.
NO CAP GUARD: never invent biography, violence, money, possessions, relationships, accomplishments or events. Mark the council no_cap_check when context is insufficient. Never imitate or copy a named artist, song, copyrighted lyric, dialogue, meme phrasing or signature cadence. Use broad creative properties only.
MODE: verse = developed thought, natural internal rhyme, transitions and punches; hook = memorable, repeatable, melodic, lower syllable density and open space; adlib = short responses, echoes, emphasis and background phrases.
VOICE: conversational, confident, observant, old-soul, dry humor, calm danger, spiritual when natural. Use “ninja” rather than the N-word. Avoid lyrical-miracle clutter and forced name-drops.
VOICE MEMO: treat transcript as imperfect source material. Preserve the user's intended slang. Infer pause/cadence from line lengths and beat data, but state timing uncertainty in pocket_summary.
EQ values are 0-100: truth governs factual grounding; pocket cadence priority; rhyme density; melody openness; punch rewind impact; culture current references; nostalgia symbolic childhood influence; space breath/rests.
NOSTALGIA useMode reference means advise only and do not place it in bars. influence permits transformed symbolic influence when natural. Culture references must be public and supplied; do not make new factual claims.
For task council, return no suggestions and a concise strategy. For predict, return exactly 3 distinct next-bar possibilities. For rewrite, return exactly 3 rewrites of rewriteBar, keeping its meaning/rhyme/cadence. Never paste a full song.`;
export function GET(){return json({ok:true,route:"/api/predict-bars",keyConfigured:Boolean(process.env.OPENAI_API_KEY),engineVersion:"rnp-adaptive-1.0"})}
export async function POST(req){if(!process.env.OPENAI_API_KEY)return json({ok:false,error:"OPENAI_API_KEY is missing in Vercel."},503);let b;try{b=await req.json()}catch{return json({ok:false,error:"Invalid Adaptive request."},400)}
 const data={task:["predict","rewrite","council"].includes(b.task)?b.task:"predict",mode:["verse","hook","adlib"].includes(b.mode)?b.mode:"verse",seed:clean(b.seed,7000),truth:clean(b.truth,9000),existingLyrics:clean(b.existingLyrics,9000),memoTranscript:clean(b.memoTranscript,7000),rewriteBar:clean(b.rewriteBar,1000),truthLock:b.truthLock!==false,eq:b.eq||{},nostalgia:{enabled:Boolean(b.nostalgia?.enabled),useMode:clean(b.nostalgia?.useMode,20),references:arr(b.nostalgia?.references),weight:clean(b.nostalgia?.weight,20),mode:clean(b.nostalgia?.mode,30),note:clean(b.nostalgia?.note,500)},culture:arr(b.culture,10),beat:b.beat||{},vibe:clean(b.vibe,100),emotionalArc:arr(b.emotionalArc,12)};
 if(data.task!=="council"&&!data.seed&&!data.memoTranscript)return json({ok:false,error:"Add a seed line or Voice Memo first."},400);
 try{const r=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-5-mini",instructions,input:JSON.stringify(data),text:{format:{type:"json_schema",name:"rnp_adaptive_output",strict:true,schema}},max_output_tokens:2400,store:false});if(!r.output_text)return json({ok:false,error:"Adaptive Intelligence returned no usable bars."},502);return json({ok:true,engineVersion:"rnp-adaptive-1.0",...JSON.parse(r.output_text)})}catch(e){console.error(e);return json({ok:false,error:e?.status===429?"Adaptive Intelligence is temporarily rate-limited.":"Adaptive Intelligence could not finish this read."},e?.status||500)}}
